--- #YAML:1.0
name: Apache2::WebApp::Plugin::File
abstract: Common methods for processing and outputting files.
version: 0.05
author:
  - Marc S. Brooks <mbrooks@cpan.org>
license: perl and artistic
distribution_type: module
requires:
  Apache2::WebApp: 0.21
  MIME::Types: 1.20
  Params::Validate: 0
build_requires:
  Apache2::Test: 0
resources:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
